import Foundation

nonisolated struct DailyDeclaration: Identifiable, Sendable {
    let id: Int
    let text: String
    let reference: String
}

nonisolated enum DeclarationLibrary {
    static let declarations: [DailyDeclaration] = [
        DailyDeclaration(id: 1, text: "Today I seek first God\u{2019}s Kingdom, and I trust Him to handle the rest.", reference: "Matthew 6:33"),
        DailyDeclaration(id: 2, text: "I am loved with an everlasting love, and I rest in it.", reference: "Jeremiah 31:3"),
        DailyDeclaration(id: 3, text: "The Lord is my Shepherd, so I will not lack.", reference: "Psalm 23:1"),
        DailyDeclaration(id: 4, text: "I am a new creation in Christ, and the old is gone.", reference: "2 Corinthians 5:17"),
        DailyDeclaration(id: 5, text: "God is with me, so I will not fear.", reference: "Isaiah 41:10"),
        DailyDeclaration(id: 6, text: "I walk by faith, not by sight, and God is leading me.", reference: "2 Corinthians 5:7"),
        DailyDeclaration(id: 7, text: "I am chosen and dearly loved by God.", reference: "Colossians 3:12"),
        DailyDeclaration(id: 8, text: "God\u{2019}s mercy is new for me this morning.", reference: "Lamentations 3:22-23"),
        DailyDeclaration(id: 9, text: "I have power, love, and self-control through the Spirit.", reference: "2 Timothy 1:7"),
        DailyDeclaration(id: 10, text: "I am forgiven and cleansed in Jesus.", reference: "1 John 1:9"),
        DailyDeclaration(id: 11, text: "The Lord is my strength today, and He sustains me.", reference: "Nehemiah 8:10"),
        DailyDeclaration(id: 12, text: "I belong to Jesus, and He holds me securely.", reference: "John 10:28"),
        DailyDeclaration(id: 13, text: "God\u{2019}s peace guards my heart and mind in Christ.", reference: "Philippians 4:7"),
        DailyDeclaration(id: 14, text: "Christ strengthens me for whatever today holds.", reference: "Philippians 4:13"),
        DailyDeclaration(id: 15, text: "God goes before me and makes a way.", reference: "Deuteronomy 31:8"),
        DailyDeclaration(id: 16, text: "I am God\u{2019}s workmanship, created for His purposes.", reference: "Ephesians 2:10"),
        DailyDeclaration(id: 17, text: "The Lord is my light, so darkness cannot overcome me.", reference: "Psalm 27:1"),
        DailyDeclaration(id: 18, text: "God will finish what He started in me.", reference: "Philippians 1:6"),
        DailyDeclaration(id: 19, text: "I am a child of God, and I am never abandoned.", reference: "Romans 8:15"),
        DailyDeclaration(id: 20, text: "The joy of the Lord is my strength.", reference: "Nehemiah 8:10"),
        DailyDeclaration(id: 21, text: "I trust the Lord with all my heart, and He directs me.", reference: "Proverbs 3:5-6"),
        DailyDeclaration(id: 22, text: "I live from victory because I am in Christ.", reference: "1 Corinthians 15:57"),
        DailyDeclaration(id: 23, text: "God\u{2019}s Word renews my mind and shapes my life.", reference: "Romans 12:2"),
        DailyDeclaration(id: 24, text: "I am more than a conqueror through Jesus\u{2019} love.", reference: "Romans 8:37"),
        DailyDeclaration(id: 25, text: "God is my refuge, and I run to Him.", reference: "Psalm 46:1"),
        DailyDeclaration(id: 26, text: "I have peace with God through faith in Jesus.", reference: "Romans 5:1"),
        DailyDeclaration(id: 27, text: "God pours His love into my heart by the Spirit.", reference: "Romans 5:5"),
        DailyDeclaration(id: 28, text: "I will be still and know God is God.", reference: "Psalm 46:10"),
        DailyDeclaration(id: 29, text: "The Lord is good, and His love toward me endures.", reference: "Psalm 136:1"),
        DailyDeclaration(id: 30, text: "I forgive because I have been forgiven.", reference: "Ephesians 4:32"),
        DailyDeclaration(id: 31, text: "I take my thoughts captive and submit them to Christ.", reference: "2 Corinthians 10:5"),
        DailyDeclaration(id: 32, text: "The Lord is my portion, and I have enough in Him.", reference: "Lamentations 3:24"),
        DailyDeclaration(id: 33, text: "I am redeemed, and my life has purpose.", reference: "Ephesians 1:7"),
        DailyDeclaration(id: 34, text: "God gives me wisdom generously when I ask.", reference: "James 1:5"),
        DailyDeclaration(id: 35, text: "I am safe under God\u{2019}s wings.", reference: "Psalm 91:4"),
        DailyDeclaration(id: 36, text: "Jesus is my firm foundation, so I will not be shaken.", reference: "Matthew 7:24-25"),
        DailyDeclaration(id: 37, text: "God works all things together for my good.", reference: "Romans 8:28"),
        DailyDeclaration(id: 38, text: "I am led by the Spirit, and I walk as God\u{2019}s child.", reference: "Romans 8:14"),
        DailyDeclaration(id: 39, text: "God heals the brokenhearted, and He is healing me.", reference: "Psalm 147:3"),
        DailyDeclaration(id: 40, text: "I am blessed with every spiritual blessing in Christ.", reference: "Ephesians 1:3"),
        DailyDeclaration(id: 41, text: "The Lord helps me, so I will not fear people.", reference: "Hebrews 13:6"),
        DailyDeclaration(id: 42, text: "I am adopted into God\u{2019}s family, and I am wanted.", reference: "Ephesians 1:5"),
        DailyDeclaration(id: 43, text: "God renews my strength, and I rise again.", reference: "Isaiah 40:31"),
        DailyDeclaration(id: 44, text: "I have the mind of Christ, and I think with truth.", reference: "1 Corinthians 2:16"),
        DailyDeclaration(id: 45, text: "God\u{2019}s grace is enough for me, and His power sustains me.", reference: "2 Corinthians 12:9"),
        DailyDeclaration(id: 46, text: "I set my mind on things above, where Christ is.", reference: "Colossians 3:1-2"),
        DailyDeclaration(id: 47, text: "The Lord fights for me, and I can be still.", reference: "Exodus 14:14"),
        DailyDeclaration(id: 48, text: "I am the righteousness of God in Christ.", reference: "2 Corinthians 5:21"),
        DailyDeclaration(id: 49, text: "I turn to God, and He welcomes me with kindness.", reference: "Romans 2:4"),
        DailyDeclaration(id: 50, text: "The Lord is near, and I draw near to Him.", reference: "James 4:8"),
        DailyDeclaration(id: 51, text: "I am the salt of the earth and the light of the world in Christ.", reference: "Matthew 5:13-14"),
        DailyDeclaration(id: 52, text: "Jesus gives me peace, so I refuse anxiety.", reference: "John 14:27"),
        DailyDeclaration(id: 53, text: "I am planted to bear fruit, and God makes me flourish.", reference: "Psalm 1:3"),
        DailyDeclaration(id: 54, text: "The Lord is my banner, and I live under His victory.", reference: "Exodus 17:15"),
        DailyDeclaration(id: 55, text: "I am fearfully and wonderfully made by God.", reference: "Psalm 139:14"),
        DailyDeclaration(id: 56, text: "God strengthens me to endure and overcome.", reference: "Isaiah 41:10"),
        DailyDeclaration(id: 57, text: "I am loved as God\u{2019}s beloved child, and I rest in it.", reference: "1 John 3:1"),
        DailyDeclaration(id: 58, text: "The Holy Spirit teaches and comforts me today.", reference: "John 14:26"),
        DailyDeclaration(id: 59, text: "God\u{2019}s Word lights my path and guides my steps.", reference: "Psalm 119:105"),
        DailyDeclaration(id: 60, text: "I am transformed by renewing my mind with truth.", reference: "Romans 12:2"),
        DailyDeclaration(id: 61, text: "I abide in Jesus, and I will bear much fruit.", reference: "John 15:5"),
        DailyDeclaration(id: 62, text: "God is my Father, and I trust His heart.", reference: "Matthew 6:9"),
        DailyDeclaration(id: 63, text: "I am called according to God\u{2019}s purpose, and my life matters.", reference: "Romans 8:28"),
        DailyDeclaration(id: 64, text: "Jesus gives rest to my soul, and I receive it.", reference: "Matthew 11:28-29"),
        DailyDeclaration(id: 65, text: "The Lord guards me, and He is my protection.", reference: "Psalm 121:7-8"),
        DailyDeclaration(id: 66, text: "God\u{2019}s timing is perfect, and I will not rush ahead.", reference: "Ecclesiastes 3:11"),
        DailyDeclaration(id: 67, text: "I live from acceptance in Christ, not striving.", reference: "Ephesians 1:6"),
        DailyDeclaration(id: 68, text: "The Lord restores my soul and leads me rightly.", reference: "Psalm 23:3"),
        DailyDeclaration(id: 69, text: "Christ in me is my hope, and I will not despair.", reference: "Colossians 1:27"),
        DailyDeclaration(id: 70, text: "God works powerfully within me beyond what I imagine.", reference: "Ephesians 3:20"),
        DailyDeclaration(id: 71, text: "I choose faith today, and I refuse fear.", reference: "Mark 5:36"),
        DailyDeclaration(id: 72, text: "Whom the Son sets free is free indeed, and that is me.", reference: "John 8:36"),
        DailyDeclaration(id: 73, text: "God gives me courage, and I take the next step.", reference: "Joshua 1:9"),
        DailyDeclaration(id: 74, text: "I am clothed with Christlike character by God\u{2019}s grace.", reference: "Colossians 3:12"),
        DailyDeclaration(id: 75, text: "God hears me when I pray, and He answers in love.", reference: "1 John 5:14"),
        DailyDeclaration(id: 76, text: "I am God\u{2019}s temple, and His Spirit lives in me.", reference: "1 Corinthians 6:19"),
        DailyDeclaration(id: 77, text: "God\u{2019}s plans for me are full of hope.", reference: "Jeremiah 29:11"),
        DailyDeclaration(id: 78, text: "I am anchored in Christ, and no storm can move me.", reference: "Hebrews 6:19"),
        DailyDeclaration(id: 79, text: "God crowns my life with love and compassion.", reference: "Psalm 103:4"),
        DailyDeclaration(id: 80, text: "I am seated with Christ in heavenly places.", reference: "Ephesians 2:6"),
        DailyDeclaration(id: 81, text: "The Lord delights in me, and He rejoices over me with singing.", reference: "Zephaniah 3:17"),
        DailyDeclaration(id: 82, text: "I am hidden with Christ in God, and I am secure.", reference: "Colossians 3:3"),
        DailyDeclaration(id: 83, text: "God supplies all my needs according to His riches.", reference: "Philippians 4:19"),
        DailyDeclaration(id: 84, text: "I am alive in Christ, and death has no power over me.", reference: "Romans 6:11"),
        DailyDeclaration(id: 85, text: "The Lord is my rock, and I stand firm on Him.", reference: "Psalm 18:2"),
        DailyDeclaration(id: 86, text: "I am set apart for God\u{2019}s glory and His good work.", reference: "2 Timothy 2:21"),
        DailyDeclaration(id: 87, text: "God\u{2019}s goodness and mercy follow me every day.", reference: "Psalm 23:6"),
        DailyDeclaration(id: 88, text: "I run with endurance the race God set before me.", reference: "Hebrews 12:1"),
        DailyDeclaration(id: 89, text: "God has not given me a spirit of fear but of power.", reference: "2 Timothy 1:7"),
        DailyDeclaration(id: 90, text: "I am complete in Christ, lacking nothing.", reference: "Colossians 2:10"),
        DailyDeclaration(id: 91, text: "The Lord makes all things beautiful in His time.", reference: "Ecclesiastes 3:11"),
        DailyDeclaration(id: 92, text: "I am kept by the power of God through faith.", reference: "1 Peter 1:5"),
        DailyDeclaration(id: 93, text: "God is faithful, and He will not let me be tempted beyond what I can bear.", reference: "1 Corinthians 10:13"),
        DailyDeclaration(id: 94, text: "I press on toward the goal for which God called me.", reference: "Philippians 3:14"),
        DailyDeclaration(id: 95, text: "The Lord surrounds me like a shield of favor.", reference: "Psalm 5:12"),
        DailyDeclaration(id: 96, text: "I am confident that God\u{2019}s promises are yes and amen.", reference: "2 Corinthians 1:20"),
        DailyDeclaration(id: 97, text: "God\u{2019}s love casts out every fear in my life.", reference: "1 John 4:18"),
        DailyDeclaration(id: 98, text: "I am an ambassador for Christ wherever I go.", reference: "2 Corinthians 5:20"),
        DailyDeclaration(id: 99, text: "The Lord is my healer, and He makes me whole.", reference: "Exodus 15:26"),
        DailyDeclaration(id: 100, text: "I overflow with hope by the power of the Holy Spirit.", reference: "Romans 15:13"),
        DailyDeclaration(id: 101, text: "God is able to do far more than I ask or think.", reference: "Ephesians 3:20"),
        DailyDeclaration(id: 102, text: "I am rooted and grounded in the love of Christ.", reference: "Ephesians 3:17"),
        DailyDeclaration(id: 103, text: "The name of the Lord is a strong tower, and I am safe.", reference: "Proverbs 18:10"),
        DailyDeclaration(id: 104, text: "I lack no good thing because the Lord is my Shepherd.", reference: "Psalm 34:10"),
        DailyDeclaration(id: 105, text: "God\u{2019}s Spirit empowers me to live boldly for Him.", reference: "Acts 1:8"),
    ]

    static func declarationForToday() -> DailyDeclaration {
        let dayOfYear = Calendar.current.ordinality(of: .day, in: .year, for: .now) ?? 1
        let index = (dayOfYear - 1) % declarations.count
        return declarations[index]
    }
}
