import Foundation

enum VerseLibrary {
    static let verses: [DailyVerse] = [
        // Day 1-10
        DailyVerse(reference: "Psalm 5:3", text: "In the morning, Lord, you hear my voice; in the morning I lay my requests before you and wait expectantly."),
        DailyVerse(reference: "Lamentations 3:22-23", text: "The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness."),
        DailyVerse(reference: "Matthew 6:33", text: "But seek first the kingdom of God and his righteousness, and all these things will be added to you."),
        DailyVerse(reference: "Isaiah 40:31", text: "But those who wait on the Lord shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary; they shall walk and not faint."),
        DailyVerse(reference: "Proverbs 3:5-6", text: "Trust in the Lord with all your heart, and do not lean on your own understanding. In all your ways acknowledge him, and he will make straight your paths."),
        DailyVerse(reference: "Philippians 4:6-7", text: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds."),
        DailyVerse(reference: "Joshua 1:9", text: "Have I not commanded you? Be strong and courageous. Do not be frightened, and do not be dismayed, for the Lord your God is with you wherever you go."),
        DailyVerse(reference: "Psalm 46:10", text: "Be still, and know that I am God. I will be exalted among the nations, I will be exalted in the earth!"),
        DailyVerse(reference: "Romans 8:28", text: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose."),
        DailyVerse(reference: "Jeremiah 29:11", text: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you a hope and a future."),
        // Day 11-20
        DailyVerse(reference: "Psalm 23:1-3", text: "The Lord is my shepherd; I shall not want. He makes me lie down in green pastures. He leads me beside still waters. He restores my soul."),
        DailyVerse(reference: "Isaiah 41:10", text: "Fear not, for I am with you; be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my righteous right hand."),
        DailyVerse(reference: "Psalm 119:105", text: "Your word is a lamp to my feet and a light to my path."),
        DailyVerse(reference: "2 Corinthians 5:7", text: "For we walk by faith, not by sight."),
        DailyVerse(reference: "Psalm 27:1", text: "The Lord is my light and my salvation; whom shall I fear? The Lord is the stronghold of my life; of whom shall I be afraid?"),
        DailyVerse(reference: "Romans 12:2", text: "Do not be conformed to this world, but be transformed by the renewal of your mind, that by testing you may discern what is the will of God, what is good and acceptable and perfect."),
        DailyVerse(reference: "Galatians 5:22-23", text: "But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control; against such things there is no law."),
        DailyVerse(reference: "Psalm 139:14", text: "I praise you, for I am fearfully and wonderfully made. Wonderful are your works; my soul knows it very well."),
        DailyVerse(reference: "Matthew 11:28-30", text: "Come to me, all who labor and are heavy laden, and I will give you rest. Take my yoke upon you, and learn from me, for I am gentle and lowly in heart, and you will find rest for your souls."),
        DailyVerse(reference: "1 John 4:19", text: "We love because he first loved us."),
        // Day 21-30
        DailyVerse(reference: "Psalm 91:1-2", text: "He who dwells in the shelter of the Most High will abide in the shadow of the Almighty. I will say to the Lord, My refuge and my fortress, my God, in whom I trust."),
        DailyVerse(reference: "Colossians 3:23", text: "Whatever you do, work heartily, as for the Lord and not for men."),
        DailyVerse(reference: "Psalm 34:8", text: "Oh, taste and see that the Lord is good! Blessed is the man who takes refuge in him!"),
        DailyVerse(reference: "John 14:27", text: "Peace I leave with you; my peace I give to you. Not as the world gives do I give to you. Let not your hearts be troubled, neither let them be afraid."),
        DailyVerse(reference: "Hebrews 11:1", text: "Now faith is the assurance of things hoped for, the conviction of things not seen."),
        DailyVerse(reference: "James 1:5", text: "If any of you lacks wisdom, let him ask God, who gives generously to all without reproach, and it will be given him."),
        DailyVerse(reference: "Psalm 37:4", text: "Delight yourself in the Lord, and he will give you the desires of your heart."),
        DailyVerse(reference: "1 Peter 5:7", text: "Cast all your anxiety on him because he cares for you."),
        DailyVerse(reference: "Ephesians 2:8-9", text: "For by grace you have been saved through faith. And this is not your own doing; it is the gift of God, not a result of works, so that no one may boast."),
        DailyVerse(reference: "Psalm 16:11", text: "You make known to me the path of life; in your presence there is fullness of joy; at your right hand are pleasures forevermore."),
        // Day 31-40
        DailyVerse(reference: "Isaiah 26:3", text: "You keep him in perfect peace whose mind is stayed on you, because he trusts in you."),
        DailyVerse(reference: "2 Timothy 1:7", text: "For God gave us a spirit not of fear but of power and love and self-control."),
        DailyVerse(reference: "Psalm 103:1-2", text: "Bless the Lord, O my soul, and all that is within me, bless his holy name! Bless the Lord, O my soul, and forget not all his benefits."),
        DailyVerse(reference: "Micah 6:8", text: "He has told you, O man, what is good; and what does the Lord require of you but to do justice, and to love kindness, and to walk humbly with your God?"),
        DailyVerse(reference: "John 15:5", text: "I am the vine; you are the branches. Whoever abides in me and I in him, he it is that bears much fruit, for apart from me you can do nothing."),
        DailyVerse(reference: "Psalm 62:1-2", text: "For God alone my soul waits in silence; from him comes my salvation. He alone is my rock and my salvation, my fortress; I shall not be greatly shaken."),
        DailyVerse(reference: "Romans 15:13", text: "May the God of hope fill you with all joy and peace in believing, so that by the power of the Holy Spirit you may abound in hope."),
        DailyVerse(reference: "Deuteronomy 31:6", text: "Be strong and courageous. Do not fear or be in dread of them, for it is the Lord your God who goes with you. He will not leave you or forsake you."),
        DailyVerse(reference: "Psalm 42:1-2", text: "As a deer pants for flowing streams, so pants my soul for you, O God. My soul thirsts for God, for the living God."),
        DailyVerse(reference: "Matthew 5:14-16", text: "You are the light of the world. A city set on a hill cannot be hidden. Let your light shine before others, so that they may see your good works and give glory to your Father who is in heaven."),
        // Day 41-50
        DailyVerse(reference: "Philippians 4:13", text: "I can do all things through him who strengthens me."),
        DailyVerse(reference: "1 Thessalonians 5:16-18", text: "Rejoice always, pray without ceasing, give thanks in all circumstances; for this is the will of God in Christ Jesus for you."),
        DailyVerse(reference: "Psalm 130:5-6", text: "I wait for the Lord, my soul waits, and in his word I hope; my soul waits for the Lord more than watchmen for the morning."),
        DailyVerse(reference: "Isaiah 43:2", text: "When you pass through the waters, I will be with you; and through the rivers, they shall not overwhelm you; when you walk through fire you shall not be burned, and the flame shall not consume you."),
        DailyVerse(reference: "John 16:33", text: "I have said these things to you, that in me you may have peace. In the world you will have tribulation. But take heart; I have overcome the world."),
        DailyVerse(reference: "Psalm 145:18", text: "The Lord is near to all who call on him, to all who call on him in truth."),
        DailyVerse(reference: "Colossians 3:15", text: "And let the peace of Christ rule in your hearts, to which indeed you were called in one body. And be thankful."),
        DailyVerse(reference: "Hebrews 12:1-2", text: "Let us run with endurance the race that is set before us, looking to Jesus, the founder and perfecter of our faith."),
        DailyVerse(reference: "Psalm 63:1", text: "O God, you are my God; earnestly I seek you; my soul thirsts for you; my flesh faints for you, as in a dry and weary land where there is no water."),
        DailyVerse(reference: "Ephesians 3:20", text: "Now to him who is able to do far more abundantly than all that we ask or think, according to the power at work within us."),
        // Day 51-60
        DailyVerse(reference: "Psalm 90:12", text: "So teach us to number our days that we may get a heart of wisdom."),
        DailyVerse(reference: "Matthew 6:6", text: "But when you pray, go into your room and shut the door and pray to your Father who is in secret. And your Father who sees in secret will reward you."),
        DailyVerse(reference: "Isaiah 55:6", text: "Seek the Lord while he may be found; call upon him while he is near."),
        DailyVerse(reference: "Romans 5:3-5", text: "We rejoice in our sufferings, knowing that suffering produces endurance, and endurance produces character, and character produces hope, and hope does not put us to shame."),
        DailyVerse(reference: "Psalm 121:1-2", text: "I lift up my eyes to the hills. From where does my help come? My help comes from the Lord, who made heaven and earth."),
        DailyVerse(reference: "John 8:12", text: "Again Jesus spoke to them, saying, I am the light of the world. Whoever follows me will not walk in darkness, but will have the light of life."),
        DailyVerse(reference: "1 Corinthians 16:13", text: "Be watchful, stand firm in the faith, act like men, be strong."),
        DailyVerse(reference: "Psalm 143:8", text: "Let me hear in the morning of your steadfast love, for in you I trust. Make me know the way I should go, for to you I lift up my soul."),
        DailyVerse(reference: "Mark 11:24", text: "Therefore I tell you, whatever you ask in prayer, believe that you have received it, and it will be yours."),
        DailyVerse(reference: "Psalm 19:14", text: "Let the words of my mouth and the meditation of my heart be acceptable in your sight, O Lord, my rock and my redeemer."),
        // Day 61-70
        DailyVerse(reference: "2 Corinthians 12:9", text: "But he said to me, My grace is sufficient for you, for my power is made perfect in weakness."),
        DailyVerse(reference: "Zephaniah 3:17", text: "The Lord your God is in your midst, a mighty one who will save; he will rejoice over you with gladness; he will quiet you by his love; he will exult over you with loud singing."),
        DailyVerse(reference: "John 10:10", text: "I came that they may have life and have it abundantly."),
        DailyVerse(reference: "Psalm 84:11", text: "For the Lord God is a sun and shield; the Lord bestows favor and honor. No good thing does he withhold from those who walk uprightly."),
        DailyVerse(reference: "Habakkuk 2:3", text: "For still the vision awaits its appointed time; it hastens to the end — it will not lie. If it seems slow, wait for it; it will surely come; it will not delay."),
        DailyVerse(reference: "Matthew 7:7", text: "Ask, and it will be given to you; seek, and you will find; knock, and it will be opened to you."),
        DailyVerse(reference: "Psalm 73:26", text: "My flesh and my heart may fail, but God is the strength of my heart and my portion forever."),
        DailyVerse(reference: "Isaiah 30:18", text: "Therefore the Lord waits to be gracious to you, and therefore he exalts himself to show mercy to you. For the Lord is a God of justice; blessed are all those who wait for him."),
        DailyVerse(reference: "Philippians 1:6", text: "And I am sure of this, that he who began a good work in you will bring it to completion at the day of Jesus Christ."),
        DailyVerse(reference: "Psalm 46:1", text: "God is our refuge and strength, a very present help in trouble."),
        // Day 71-80
        DailyVerse(reference: "1 John 1:9", text: "If we confess our sins, he is faithful and just to forgive us our sins and to cleanse us from all unrighteousness."),
        DailyVerse(reference: "Proverbs 16:3", text: "Commit your works to the Lord, and your plans will be established."),
        DailyVerse(reference: "Psalm 118:24", text: "This is the day that the Lord has made; let us rejoice and be glad in it."),
        DailyVerse(reference: "John 1:5", text: "The light shines in the darkness, and the darkness has not overcome it."),
        DailyVerse(reference: "Romans 8:38-39", text: "For I am sure that neither death nor life, nor angels nor rulers, nor things present nor things to come, nor powers, nor height nor depth, nor anything else in all creation, will be able to separate us from the love of God."),
        DailyVerse(reference: "Psalm 51:10", text: "Create in me a clean heart, O God, and renew a right spirit within me."),
        DailyVerse(reference: "Hebrews 4:16", text: "Let us then with confidence draw near to the throne of grace, that we may receive mercy and find grace to help in time of need."),
        DailyVerse(reference: "Isaiah 40:29", text: "He gives power to the faint, and to him who has no might he increases strength."),
        DailyVerse(reference: "Matthew 28:20", text: "And behold, I am with you always, to the end of the age."),
        DailyVerse(reference: "Psalm 55:22", text: "Cast your burden on the Lord, and he will sustain you; he will never permit the righteous to be moved."),
        // Day 81-92 (remaining original)
        DailyVerse(reference: "Nahum 1:7", text: "The Lord is good, a stronghold in the day of trouble; he knows those who take refuge in him."),
        DailyVerse(reference: "James 4:8", text: "Draw near to God, and he will draw near to you."),
        DailyVerse(reference: "Psalm 36:5-6", text: "Your steadfast love, O Lord, extends to the heavens, your faithfulness to the clouds. Your righteousness is like the mountains of God; your judgments are like the great deep."),
        DailyVerse(reference: "Ephesians 6:10", text: "Finally, be strong in the Lord and in the strength of his might."),
        DailyVerse(reference: "Psalm 147:3", text: "He heals the brokenhearted and binds up their wounds."),
        DailyVerse(reference: "John 14:1", text: "Let not your hearts be troubled. Believe in God; believe also in me."),
        DailyVerse(reference: "Proverbs 18:10", text: "The name of the Lord is a strong tower; the righteous man runs into it and is safe."),
        DailyVerse(reference: "Psalm 100:4-5", text: "Enter his gates with thanksgiving, and his courts with praise! Give thanks to him; bless his name! For the Lord is good; his steadfast love endures forever."),
        DailyVerse(reference: "Isaiah 58:11", text: "And the Lord will guide you continually and satisfy your desire in scorched places and make your bones strong; and you shall be like a watered garden, like a spring of water, whose waters do not fail."),
        DailyVerse(reference: "Romans 8:26", text: "Likewise the Spirit helps us in our weakness. For we do not know what to pray for as we ought, but the Spirit himself intercedes for us with groanings too deep for words."),
        DailyVerse(reference: "Psalm 40:1-2", text: "I waited patiently for the Lord; he inclined to me and heard my cry. He drew me up from the pit of destruction, out of the miry bog, and set my feet upon a rock, making my steps secure."),
        DailyVerse(reference: "Genesis 1:27", text: "So God created man in his own image, in the image of God he created him; male and female he created them."),
        // Day 93-120
        DailyVerse(reference: "Psalm 1:1-2", text: "Blessed is the man who walks not in the counsel of the wicked, nor stands in the way of sinners, nor sits in the seat of scoffers; but his delight is in the law of the Lord, and on his law he meditates day and night."),
        DailyVerse(reference: "Psalm 4:8", text: "In peace I will both lie down and sleep; for you alone, O Lord, make me dwell in safety."),
        DailyVerse(reference: "Psalm 8:3-4", text: "When I look at your heavens, the work of your fingers, the moon and the stars, which you have set in place, what is man that you are mindful of him, and the son of man that you care for him?"),
        DailyVerse(reference: "Psalm 9:9-10", text: "The Lord is a stronghold for the oppressed, a stronghold in times of trouble. And those who know your name put their trust in you, for you, O Lord, have not forsaken those who seek you."),
        DailyVerse(reference: "Psalm 13:5-6", text: "But I have trusted in your steadfast love; my heart shall rejoice in your salvation. I will sing to the Lord, because he has dealt bountifully with me."),
        DailyVerse(reference: "Psalm 18:2", text: "The Lord is my rock and my fortress and my deliverer, my God, my rock, in whom I take refuge, my shield, and the horn of my salvation, my stronghold."),
        DailyVerse(reference: "Psalm 20:7", text: "Some trust in chariots and some in horses, but we trust in the name of the Lord our God."),
        DailyVerse(reference: "Psalm 25:4-5", text: "Make me to know your ways, O Lord; teach me your paths. Lead me in your truth and teach me, for you are the God of my salvation; for you I wait all the day long."),
        DailyVerse(reference: "Psalm 27:4", text: "One thing have I asked of the Lord, that will I seek after: that I may dwell in the house of the Lord all the days of my life, to gaze upon the beauty of the Lord and to inquire in his temple."),
        DailyVerse(reference: "Psalm 28:7", text: "The Lord is my strength and my shield; in him my heart trusts, and I am helped; my heart exults, and with my song I give thanks to him."),
        DailyVerse(reference: "Psalm 29:11", text: "May the Lord give strength to his people! May the Lord bless his people with peace!"),
        DailyVerse(reference: "Psalm 30:5", text: "For his anger is but for a moment, and his favor is for a lifetime. Weeping may tarry for the night, but joy comes with the morning."),
        DailyVerse(reference: "Psalm 31:24", text: "Be strong, and let your heart take courage, all you who wait for the Lord!"),
        DailyVerse(reference: "Psalm 32:8", text: "I will instruct you and teach you in the way you should go; I will counsel you with my eye upon you."),
        DailyVerse(reference: "Psalm 33:4-5", text: "For the word of the Lord is upright, and all his work is done in faithfulness. He loves righteousness and justice; the earth is full of the steadfast love of the Lord."),
        DailyVerse(reference: "Psalm 34:17-18", text: "When the righteous cry for help, the Lord hears and delivers them out of all their troubles. The Lord is near to the brokenhearted and saves the crushed in spirit."),
        DailyVerse(reference: "Psalm 37:5-6", text: "Commit your way to the Lord; trust in him, and he will act. He will bring forth your righteousness as the light, and your justice as the noonday."),
        DailyVerse(reference: "Psalm 37:23-24", text: "The steps of a man are established by the Lord, when he delights in his way; though he fall, he shall not be cast headlong, for the Lord upholds his hand."),
        DailyVerse(reference: "Psalm 39:7", text: "And now, O Lord, for what do I wait? My hope is in you."),
        DailyVerse(reference: "Psalm 46:5", text: "God is in the midst of her; she shall not be moved; God will help her when morning dawns."),
        DailyVerse(reference: "Psalm 56:3-4", text: "When I am afraid, I put my trust in you. In God, whose word I praise, in God I trust; I shall not be afraid. What can flesh do to me?"),
        DailyVerse(reference: "Psalm 57:1", text: "Be merciful to me, O God, be merciful to me, for in you my soul takes refuge; in the shadow of your wings I will take refuge, till the storms of destruction pass by."),
        DailyVerse(reference: "Psalm 59:16", text: "But I will sing of your strength; I will sing aloud of your steadfast love in the morning. For you have been to me a fortress and a refuge in the day of my distress."),
        DailyVerse(reference: "Psalm 61:2-3", text: "From the end of the earth I call to you when my heart is faint. Lead me to the rock that is higher than I, for you have been my refuge, a strong tower against the enemy."),
        DailyVerse(reference: "Psalm 62:5-6", text: "For God alone, O my soul, wait in silence, for my hope is from him. He only is my rock and my salvation, my fortress; I shall not be shaken."),
        DailyVerse(reference: "Psalm 63:3", text: "Because your steadfast love is better than life, my lips will praise you."),
        DailyVerse(reference: "Psalm 65:4", text: "Blessed is the one you choose and bring near, to dwell in your courts! We shall be satisfied with the goodness of your house, the holiness of your temple!"),
        DailyVerse(reference: "Psalm 66:1-2", text: "Shout for joy to God, all the earth; sing the glory of his name; give to him glorious praise!"),
        // Day 121-150
        DailyVerse(reference: "Psalm 68:19", text: "Blessed be the Lord, who daily bears us up; God is our salvation."),
        DailyVerse(reference: "Psalm 71:5", text: "For you, O Lord, are my hope, my trust, O Lord, from my youth."),
        DailyVerse(reference: "Psalm 77:11-12", text: "I will remember the deeds of the Lord; yes, I will remember your wonders of old. I will ponder all your work, and meditate on your mighty deeds."),
        DailyVerse(reference: "Psalm 84:1-2", text: "How lovely is your dwelling place, O Lord of hosts! My soul longs, yes, faints for the courts of the Lord; my heart and flesh sing for joy to the living God."),
        DailyVerse(reference: "Psalm 86:5", text: "For you, O Lord, are good and forgiving, abounding in steadfast love to all who call upon you."),
        DailyVerse(reference: "Psalm 86:11", text: "Teach me your way, O Lord, that I may walk in your truth; unite my heart to fear your name."),
        DailyVerse(reference: "Psalm 89:1", text: "I will sing of the steadfast love of the Lord, forever; with my mouth I will make known your faithfulness to all generations."),
        DailyVerse(reference: "Psalm 90:1-2", text: "Lord, you have been our dwelling place in all generations. Before the mountains were brought forth, or ever you had formed the earth and the world, from everlasting to everlasting you are God."),
        DailyVerse(reference: "Psalm 91:4", text: "He will cover you with his pinions, and under his wings you will find refuge; his faithfulness is a shield and buckler."),
        DailyVerse(reference: "Psalm 91:11", text: "For he will command his angels concerning you to guard you in all your ways."),
        DailyVerse(reference: "Psalm 92:1-2", text: "It is good to give thanks to the Lord, to sing praises to your name, O Most High; to declare your steadfast love in the morning, and your faithfulness by night."),
        DailyVerse(reference: "Psalm 95:1-2", text: "Oh come, let us sing to the Lord; let us make a joyful noise to the rock of our salvation! Let us come into his presence with thanksgiving."),
        DailyVerse(reference: "Psalm 96:1-2", text: "Oh sing to the Lord a new song; sing to the Lord, all the earth! Sing to the Lord, bless his name; tell of his salvation from day to day!"),
        DailyVerse(reference: "Psalm 97:11-12", text: "Light is sown for the righteous, and joy for the upright in heart. Rejoice in the Lord, O you righteous, and give thanks to his holy name!"),
        DailyVerse(reference: "Psalm 98:1", text: "Oh sing to the Lord a new song, for he has done marvelous things! His right hand and his holy arm have worked salvation for him."),
        DailyVerse(reference: "Psalm 103:8", text: "The Lord is merciful and gracious, slow to anger and abounding in steadfast love."),
        DailyVerse(reference: "Psalm 103:11-12", text: "For as high as the heavens are above the earth, so great is his steadfast love toward those who fear him; as far as the east is from the west, so far does he remove our transgressions from us."),
        DailyVerse(reference: "Psalm 104:33-34", text: "I will sing to the Lord as long as I live; I will sing praise to my God while I have being. May my meditation be pleasing to him, for I rejoice in the Lord."),
        DailyVerse(reference: "Psalm 107:1", text: "Oh give thanks to the Lord, for he is good, for his steadfast love endures forever!"),
        DailyVerse(reference: "Psalm 111:10", text: "The fear of the Lord is the beginning of wisdom; all those who practice it have a good understanding. His praise endures forever!"),
        DailyVerse(reference: "Psalm 112:1", text: "Praise the Lord! Blessed is the man who fears the Lord, who greatly delights in his commandments!"),
        DailyVerse(reference: "Psalm 115:1", text: "Not to us, O Lord, not to us, but to your name give glory, for the sake of your steadfast love and your faithfulness!"),
        DailyVerse(reference: "Psalm 116:1-2", text: "I love the Lord, because he has heard my voice and my pleas for mercy. Because he inclined his ear to me, therefore I will call on him as long as I live."),
        DailyVerse(reference: "Psalm 119:11", text: "I have stored up your word in my heart, that I might not sin against you."),
        DailyVerse(reference: "Psalm 119:50", text: "This is my comfort in my affliction, that your promise gives me life."),
        DailyVerse(reference: "Psalm 119:114", text: "You are my hiding place and my shield; I hope in your word."),
        DailyVerse(reference: "Psalm 119:130", text: "The unfolding of your words gives light; it imparts understanding to the simple."),
        DailyVerse(reference: "Psalm 121:7-8", text: "The Lord will keep you from all evil; he will keep your life. The Lord will keep your going out and your coming in from this time forth and forevermore."),
        DailyVerse(reference: "Psalm 126:5-6", text: "Those who sow in tears shall reap with shouts of joy! He who goes out weeping, bearing the seed for sowing, shall come home with shouts of joy, bringing his sheaves with him."),
        DailyVerse(reference: "Psalm 133:1", text: "Behold, how good and pleasant it is when brothers dwell in unity!"),
        // Day 151-180
        DailyVerse(reference: "Psalm 138:3", text: "On the day I called, you answered me; my strength of soul you increased."),
        DailyVerse(reference: "Psalm 139:7-8", text: "Where shall I go from your Spirit? Or where shall I flee from your presence? If I ascend to heaven, you are there! If I make my bed in Sheol, you are there!"),
        DailyVerse(reference: "Psalm 139:23-24", text: "Search me, O God, and know my heart! Try me and know my thoughts! And see if there be any grievous way in me, and lead me in the way everlasting!"),
        DailyVerse(reference: "Psalm 141:2", text: "Let my prayer be counted as incense before you, and the lifting up of my hands as the evening sacrifice!"),
        DailyVerse(reference: "Psalm 143:10", text: "Teach me to do your will, for you are my God! Let your good Spirit lead me on level ground!"),
        DailyVerse(reference: "Psalm 144:1-2", text: "Blessed be the Lord, my rock, who trains my hands for war, and my fingers for battle; he is my steadfast love and my fortress, my stronghold and my deliverer."),
        DailyVerse(reference: "Psalm 145:8-9", text: "The Lord is gracious and merciful, slow to anger and abounding in steadfast love. The Lord is good to all, and his mercy is over all that he has made."),
        DailyVerse(reference: "Psalm 146:5-6", text: "Blessed is he whose help is the God of Jacob, whose hope is in the Lord his God, who made heaven and earth, the sea, and all that is in them, who keeps faith forever."),
        DailyVerse(reference: "Psalm 147:5", text: "Great is our Lord, and abundant in power; his understanding is beyond measure."),
        DailyVerse(reference: "Psalm 148:13", text: "Let them praise the name of the Lord, for his name alone is exalted; his majesty is above earth and heaven."),
        DailyVerse(reference: "Psalm 150:6", text: "Let everything that has breath praise the Lord! Praise the Lord!"),
        DailyVerse(reference: "Proverbs 2:6", text: "For the Lord gives wisdom; from his mouth come knowledge and understanding."),
        DailyVerse(reference: "Proverbs 3:3-4", text: "Let not steadfast love and faithfulness forsake you; bind them around your neck; write them on the tablet of your heart. So you will find favor and good success in the sight of God and man."),
        DailyVerse(reference: "Proverbs 4:23", text: "Keep your heart with all vigilance, for from it flow the springs of life."),
        DailyVerse(reference: "Proverbs 10:22", text: "The blessing of the Lord makes rich, and he adds no sorrow with it."),
        DailyVerse(reference: "Proverbs 11:25", text: "Whoever brings blessing will be enriched, and one who waters will himself be watered."),
        DailyVerse(reference: "Proverbs 12:25", text: "Anxiety in a man's heart weighs him down, but a good word makes him glad."),
        DailyVerse(reference: "Proverbs 14:26", text: "In the fear of the Lord one has strong confidence, and his children will have a refuge."),
        DailyVerse(reference: "Proverbs 15:1", text: "A soft answer turns away wrath, but a harsh word stirs up anger."),
        DailyVerse(reference: "Proverbs 15:13", text: "A glad heart makes a cheerful face, but by sorrow of heart the spirit is crushed."),
        DailyVerse(reference: "Proverbs 16:9", text: "The heart of man plans his way, but the Lord establishes his steps."),
        DailyVerse(reference: "Proverbs 17:17", text: "A friend loves at all times, and a brother is born for adversity."),
        DailyVerse(reference: "Proverbs 19:21", text: "Many are the plans in the mind of a man, but it is the purpose of the Lord that will stand."),
        DailyVerse(reference: "Proverbs 22:6", text: "Train up a child in the way he should go; even when he is old he will not depart from it."),
        DailyVerse(reference: "Proverbs 27:17", text: "Iron sharpens iron, and one man sharpens another."),
        DailyVerse(reference: "Proverbs 31:25", text: "Strength and dignity are her clothing, and she laughs at the time to come."),
        DailyVerse(reference: "Proverbs 3:9-10", text: "Honor the Lord with your wealth and with the firstfruits of all your produce; then your barns will be filled with plenty, and your vats will be bursting with wine."),
        DailyVerse(reference: "Proverbs 28:26", text: "Whoever trusts in his own mind is a fool, but he who walks in wisdom will be delivered."),
        DailyVerse(reference: "Proverbs 16:24", text: "Gracious words are like a honeycomb, sweetness to the soul and health to the body."),
        DailyVerse(reference: "Proverbs 20:24", text: "A man's steps are from the Lord; how then can man understand his way?"),
        // Day 181-210
        DailyVerse(reference: "Isaiah 9:6", text: "For to us a child is born, to us a son is given; and the government shall be upon his shoulder, and his name shall be called Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace."),
        DailyVerse(reference: "Isaiah 12:2", text: "Behold, God is my salvation; I will trust, and will not be afraid; for the Lord God is my strength and my song, and he has become my salvation."),
        DailyVerse(reference: "Isaiah 25:1", text: "O Lord, you are my God; I will exalt you; I will praise your name, for you have done wonderful things, plans formed of old, faithful and sure."),
        DailyVerse(reference: "Isaiah 26:4", text: "Trust in the Lord forever, for the Lord God is an everlasting rock."),
        DailyVerse(reference: "Isaiah 30:15", text: "In returning and rest you shall be saved; in quietness and in trust shall be your strength."),
        DailyVerse(reference: "Isaiah 32:17", text: "And the effect of righteousness will be peace, and the result of righteousness, quietness and trust forever."),
        DailyVerse(reference: "Isaiah 33:6", text: "And he will be the stability of your times, abundance of salvation, wisdom, and knowledge; the fear of the Lord is Zion's treasure."),
        DailyVerse(reference: "Isaiah 35:4", text: "Say to those who have an anxious heart, Be strong; fear not! Behold, your God will come with vengeance, with the recompense of God. He will come and save you."),
        DailyVerse(reference: "Isaiah 40:8", text: "The grass withers, the flower fades, but the word of our God will stand forever."),
        DailyVerse(reference: "Isaiah 41:13", text: "For I, the Lord your God, hold your right hand; it is I who say to you, Fear not, I am the one who helps you."),
        DailyVerse(reference: "Isaiah 43:19", text: "Behold, I am doing a new thing; now it springs forth, do you not perceive it? I will make a way in the wilderness and rivers in the desert."),
        DailyVerse(reference: "Isaiah 44:3", text: "For I will pour water on the thirsty land, and streams on the dry ground; I will pour my Spirit upon your offspring, and my blessing on your descendants."),
        DailyVerse(reference: "Isaiah 46:4", text: "Even to your old age I am he, and to gray hairs I will carry you. I have made, and I will bear; I will carry and will save."),
        DailyVerse(reference: "Isaiah 48:17", text: "Thus says the Lord, your Redeemer, the Holy One of Israel: I am the Lord your God, who teaches you to profit, who leads you in the way you should go."),
        DailyVerse(reference: "Isaiah 49:15-16", text: "Can a woman forget her nursing child, that she should have no compassion on the son of her womb? Even these may forget, yet I will not forget you. Behold, I have engraved you on the palms of my hands."),
        DailyVerse(reference: "Isaiah 53:5", text: "But he was pierced for our transgressions; he was crushed for our iniquities; upon him was the chastisement that brought us peace, and with his wounds we are healed."),
        DailyVerse(reference: "Isaiah 54:10", text: "For the mountains may depart and the hills be removed, but my steadfast love shall not depart from you, and my covenant of peace shall not be removed, says the Lord, who has compassion on you."),
        DailyVerse(reference: "Isaiah 55:8-9", text: "For my thoughts are not your thoughts, neither are your ways my ways, declares the Lord. For as the heavens are higher than the earth, so are my ways higher than your ways and my thoughts than your thoughts."),
        DailyVerse(reference: "Isaiah 55:12", text: "For you shall go out in joy and be led forth in peace; the mountains and the hills before you shall break forth into singing, and all the trees of the field shall clap their hands."),
        DailyVerse(reference: "Isaiah 61:1", text: "The Spirit of the Lord God is upon me, because the Lord has anointed me to bring good news to the poor; he has sent me to bind up the brokenhearted, to proclaim liberty to the captives."),
        DailyVerse(reference: "Isaiah 61:3", text: "To grant to those who mourn in Zion — to give them a beautiful headdress instead of ashes, the oil of gladness instead of mourning, the garment of praise instead of a faint spirit."),
        DailyVerse(reference: "Isaiah 64:8", text: "But now, O Lord, you are our Father; we are the clay, and you are our potter; we are all the work of your hand."),
        DailyVerse(reference: "Isaiah 65:24", text: "Before they call I will answer; while they are yet speaking I will hear."),
        DailyVerse(reference: "Jeremiah 17:7-8", text: "Blessed is the man who trusts in the Lord, whose trust is the Lord. He is like a tree planted by water, that sends out its roots by the stream."),
        DailyVerse(reference: "Jeremiah 31:3", text: "I have loved you with an everlasting love; therefore I have continued my faithfulness to you."),
        DailyVerse(reference: "Jeremiah 33:3", text: "Call to me and I will answer you, and will tell you great and hidden things that you have not known."),
        DailyVerse(reference: "Ezekiel 36:26", text: "And I will give you a new heart, and a new spirit I will put within you. And I will remove the heart of stone from your flesh and give you a heart of flesh."),
        DailyVerse(reference: "Daniel 2:20-21", text: "Blessed be the name of God forever and ever, to whom belong wisdom and might. He changes times and seasons; he removes kings and sets up kings; he gives wisdom to the wise."),
        DailyVerse(reference: "Hosea 6:3", text: "Let us know; let us press on to know the Lord; his going out is sure as the dawn; he will come to us as the showers, as the spring rains that water the earth."),
        DailyVerse(reference: "Joel 2:25", text: "I will restore to you the years that the swarming locust has eaten, the hopper, the destroyer, and the cutter, my great army, which I sent among you."),
        // Day 211-240
        DailyVerse(reference: "Malachi 3:10", text: "Bring the full tithe into the storehouse, that there may be food in my house. And thereby put me to the test, says the Lord of hosts, if I will not open the windows of heaven for you and pour down for you a blessing until there is no more need."),
        DailyVerse(reference: "Genesis 28:15", text: "Behold, I am with you and will keep you wherever you go, and will bring you back to this land. For I will not leave you until I have done what I have promised you."),
        DailyVerse(reference: "Genesis 50:20", text: "As for you, you meant evil against me, but God meant it for good, to bring it about that many people should be kept alive, as they are today."),
        DailyVerse(reference: "Exodus 14:14", text: "The Lord will fight for you, and you have only to be silent."),
        DailyVerse(reference: "Exodus 15:2", text: "The Lord is my strength and my song, and he has become my salvation; this is my God, and I will praise him, my father's God, and I will exalt him."),
        DailyVerse(reference: "Exodus 33:14", text: "And he said, My presence will go with you, and I will give you rest."),
        DailyVerse(reference: "Numbers 6:24-26", text: "The Lord bless you and keep you; the Lord make his face to shine upon you and be gracious to you; the Lord lift up his countenance upon you and give you peace."),
        DailyVerse(reference: "Deuteronomy 7:9", text: "Know therefore that the Lord your God is God, the faithful God who keeps covenant and steadfast love with those who love him and keep his commandments, to a thousand generations."),
        DailyVerse(reference: "Deuteronomy 10:12", text: "And now, Israel, what does the Lord your God require of you, but to fear the Lord your God, to walk in all his ways, to love him, to serve the Lord your God with all your heart and with all your soul."),
        DailyVerse(reference: "Deuteronomy 33:27", text: "The eternal God is your refuge, and underneath are the everlasting arms. And he thrust out the enemy before you and said, Destroy."),
        DailyVerse(reference: "Joshua 24:15", text: "But as for me and my house, we will serve the Lord."),
        DailyVerse(reference: "1 Samuel 16:7", text: "For the Lord sees not as man sees: man looks on the outward appearance, but the Lord looks on the heart."),
        DailyVerse(reference: "2 Samuel 22:31", text: "This God — his way is perfect; the word of the Lord proves true; he is a shield for all those who take refuge in him."),
        DailyVerse(reference: "1 Kings 8:56", text: "Blessed be the Lord who has given rest to his people Israel, according to all that he promised. Not one word has failed of all his good promise."),
        DailyVerse(reference: "2 Chronicles 7:14", text: "If my people who are called by my name humble themselves, and pray and seek my face and turn from their wicked ways, then I will hear from heaven and will forgive their sin and heal their land."),
        DailyVerse(reference: "2 Chronicles 16:9", text: "For the eyes of the Lord run to and fro throughout the whole earth, to give strong support to those whose heart is blameless toward him."),
        DailyVerse(reference: "Nehemiah 8:10", text: "Do not be grieved, for the joy of the Lord is your strength."),
        DailyVerse(reference: "Job 19:25", text: "For I know that my Redeemer lives, and at the last he will stand upon the earth."),
        DailyVerse(reference: "Job 23:10", text: "But he knows the way that I take; when he has tried me, I shall come out as gold."),
        DailyVerse(reference: "Ecclesiastes 3:1", text: "For everything there is a season, and a time for every matter under heaven."),
        DailyVerse(reference: "Ecclesiastes 3:11", text: "He has made everything beautiful in its time. Also, he has put eternity into man's heart, yet so that he cannot find out what God has done from the beginning to the end."),
        DailyVerse(reference: "Song of Solomon 2:4", text: "He brought me to the banqueting house, and his banner over me was love."),
        DailyVerse(reference: "Daniel 10:19", text: "And he said, O man greatly loved, fear not, peace be with you; be strong and of good courage."),
        DailyVerse(reference: "Amos 5:24", text: "But let justice roll down like waters, and righteousness like an ever-flowing stream."),
        DailyVerse(reference: "Jonah 2:2", text: "I called out to the Lord, out of my distress, and he answered me; out of the belly of Sheol I cried, and you heard my voice."),
        DailyVerse(reference: "Ecclesiastes 7:8", text: "Better is the end of a thing than its beginning, and the patient in spirit is better than the proud in spirit."),
        DailyVerse(reference: "Daniel 3:17-18", text: "Our God whom we serve is able to deliver us from the burning fiery furnace, and he will deliver us out of your hand, O king. But if not, be it known to you, O king, that we will not serve your gods."),
        DailyVerse(reference: "Song of Solomon 8:7", text: "Many waters cannot quench love, neither can floods drown it. If a man offered for love all the wealth of his house, he would be utterly despised."),
        DailyVerse(reference: "Daniel 6:26-27", text: "He is the living God, enduring forever; his kingdom shall never be destroyed, and his dominion shall be to the end. He delivers and rescues; he works signs and wonders in heaven and on earth."),
        DailyVerse(reference: "Ezekiel 37:5-6", text: "Thus says the Lord God to these bones: Behold, I will cause breath to enter you, and you shall live. And I will lay sinews upon you, and will cause flesh to come upon you."),
        // Day 241-270
        DailyVerse(reference: "Matthew 5:6", text: "Blessed are those who hunger and thirst for righteousness, for they shall be satisfied."),
        DailyVerse(reference: "Matthew 5:8", text: "Blessed are the pure in heart, for they shall see God."),
        DailyVerse(reference: "Matthew 5:9", text: "Blessed are the peacemakers, for they shall be called sons of God."),
        DailyVerse(reference: "Matthew 6:21", text: "For where your treasure is, there your heart will be also."),
        DailyVerse(reference: "Matthew 6:25-26", text: "Therefore I tell you, do not be anxious about your life, what you will eat or what you will drink. Look at the birds of the air: they neither sow nor reap, yet your heavenly Father feeds them. Are you not of more value than they?"),
        DailyVerse(reference: "Matthew 6:34", text: "Therefore do not be anxious about tomorrow, for tomorrow will be anxious for itself. Sufficient for the day is its own trouble."),
        DailyVerse(reference: "Matthew 10:29-31", text: "Are not two sparrows sold for a penny? And not one of them will fall to the ground apart from your Father. Fear not, therefore; you are of more value than many sparrows."),
        DailyVerse(reference: "Matthew 17:20", text: "For truly, I say to you, if you have faith like a grain of mustard seed, you will say to this mountain, Move from here to there, and it will move, and nothing will be impossible for you."),
        DailyVerse(reference: "Matthew 18:20", text: "For where two or three are gathered in my name, there am I among them."),
        DailyVerse(reference: "Matthew 19:26", text: "But Jesus looked at them and said, With man this is impossible, but with God all things are possible."),
        DailyVerse(reference: "Matthew 22:37-38", text: "You shall love the Lord your God with all your heart and with all your soul and with all your mind. This is the great and first commandment."),
        DailyVerse(reference: "Mark 9:23", text: "And Jesus said to him, If you can! All things are possible for one who believes."),
        DailyVerse(reference: "Mark 10:27", text: "Jesus looked at them and said, With man it is impossible, but not with God. For all things are possible with God."),
        DailyVerse(reference: "Mark 11:22", text: "And Jesus answered them, Have faith in God."),
        DailyVerse(reference: "Luke 1:37", text: "For nothing will be impossible with God."),
        DailyVerse(reference: "Luke 1:46-47", text: "And Mary said, My soul magnifies the Lord, and my spirit rejoices in God my Savior."),
        DailyVerse(reference: "Luke 6:38", text: "Give, and it will be given to you. Good measure, pressed down, shaken together, running over, will be put into your lap. For with the measure you use it will be measured back to you."),
        DailyVerse(reference: "Luke 11:9-10", text: "And I tell you, ask, and it will be given to you; seek, and you will find; knock, and it will be opened to you. For everyone who asks receives."),
        DailyVerse(reference: "Luke 12:32", text: "Fear not, little flock, for it is your Father's good pleasure to give you the kingdom."),
        DailyVerse(reference: "Luke 15:7", text: "Just so, I tell you, there will be more joy in heaven over one sinner who repents than over ninety-nine righteous persons who need no repentance."),
        DailyVerse(reference: "Luke 18:27", text: "But he said, What is impossible with man is possible with God."),
        DailyVerse(reference: "John 1:12", text: "But to all who did receive him, who believed in his name, he gave the right to become children of God."),
        DailyVerse(reference: "John 3:16", text: "For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life."),
        DailyVerse(reference: "John 4:14", text: "But whoever drinks of the water that I will give him will never be thirsty again. The water that I will give him will become in him a spring of water welling up to eternal life."),
        DailyVerse(reference: "John 6:35", text: "Jesus said to them, I am the bread of life; whoever comes to me shall not hunger, and whoever believes in me shall never thirst."),
        DailyVerse(reference: "John 7:38", text: "Whoever believes in me, as the Scripture has said, Out of his heart will flow rivers of living water."),
        DailyVerse(reference: "John 8:32", text: "And you will know the truth, and the truth will set you free."),
        DailyVerse(reference: "John 8:36", text: "So if the Son sets you free, you will be free indeed."),
        DailyVerse(reference: "John 10:27-28", text: "My sheep hear my voice, and I know them, and they follow me. I give them eternal life, and they will never perish, and no one will snatch them out of my hand."),
        DailyVerse(reference: "John 11:25-26", text: "Jesus said to her, I am the resurrection and the life. Whoever believes in me, though he die, yet shall he live, and everyone who lives and believes in me shall never die."),
        // Day 271-300
        DailyVerse(reference: "John 13:34-35", text: "A new commandment I give to you, that you love one another: just as I have loved you, you also are to love one another. By this all people will know that you are my disciples."),
        DailyVerse(reference: "John 14:6", text: "Jesus said to him, I am the way, and the truth, and the life. No one comes to the Father except through me."),
        DailyVerse(reference: "John 14:13-14", text: "Whatever you ask in my name, this I will do, that the Father may be glorified in the Son. If you ask me anything in my name, I will do it."),
        DailyVerse(reference: "John 15:9", text: "As the Father has loved me, so have I loved you. Abide in my love."),
        DailyVerse(reference: "John 15:12-13", text: "This is my commandment, that you love one another as I have loved you. Greater love has no one than this, that someone lay down his life for his friends."),
        DailyVerse(reference: "John 15:16", text: "You did not choose me, but I chose you and appointed you that you should go and bear fruit and that your fruit should abide."),
        DailyVerse(reference: "John 16:24", text: "Until now you have asked nothing in my name. Ask, and you will receive, that your joy may be full."),
        DailyVerse(reference: "John 17:17", text: "Sanctify them in the truth; your word is truth."),
        DailyVerse(reference: "Acts 1:8", text: "But you will receive power when the Holy Spirit has come upon you, and you will be my witnesses in Jerusalem and in all Judea and Samaria, and to the end of the earth."),
        DailyVerse(reference: "Acts 4:12", text: "And there is salvation in no one else, for there is no other name under heaven given among men by which we must be saved."),
        DailyVerse(reference: "Acts 17:28", text: "For in him we live and move and have our being."),
        DailyVerse(reference: "Acts 20:24", text: "But I do not account my life of any value nor as precious to myself, if only I may finish my course and the ministry that I received from the Lord Jesus, to testify to the gospel of the grace of God."),
        DailyVerse(reference: "Romans 1:16", text: "For I am not ashamed of the gospel, for it is the power of God for salvation to everyone who believes."),
        DailyVerse(reference: "Romans 5:1", text: "Therefore, since we have been justified by faith, we have peace with God through our Lord Jesus Christ."),
        DailyVerse(reference: "Romans 5:8", text: "But God shows his love for us in that while we were still sinners, Christ died for us."),
        DailyVerse(reference: "Romans 6:23", text: "For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord."),
        DailyVerse(reference: "Romans 8:1", text: "There is therefore now no condemnation for those who are in Christ Jesus."),
        DailyVerse(reference: "Romans 8:11", text: "If the Spirit of him who raised Jesus from the dead dwells in you, he who raised Christ Jesus from the dead will also give life to your mortal bodies through his Spirit who dwells in you."),
        DailyVerse(reference: "Romans 8:31", text: "What then shall we say to these things? If God is for us, who can be against us?"),
        DailyVerse(reference: "Romans 8:37", text: "No, in all these things we are more than conquerors through him who loved us."),
        DailyVerse(reference: "Romans 10:9-10", text: "Because, if you confess with your mouth that Jesus is Lord and believe in your heart that God raised him from the dead, you will be saved."),
        DailyVerse(reference: "Romans 10:17", text: "So faith comes from hearing, and hearing through the word of Christ."),
        DailyVerse(reference: "Romans 11:33", text: "Oh, the depth of the riches and wisdom and knowledge of God! How unsearchable are his judgments and how inscrutable his ways!"),
        DailyVerse(reference: "Romans 12:1", text: "I appeal to you therefore, brothers, by the mercies of God, to present your bodies as a living sacrifice, holy and acceptable to God, which is your spiritual worship."),
        DailyVerse(reference: "Romans 12:9-10", text: "Let love be genuine. Abhor what is evil; hold fast to what is good. Love one another with brotherly affection. Outdo one another in showing honor."),
        DailyVerse(reference: "Romans 12:12", text: "Rejoice in hope, be patient in tribulation, be constant in prayer."),
        DailyVerse(reference: "Romans 14:8", text: "For if we live, we live to the Lord, and if we die, we die to the Lord. So then, whether we live or whether we die, we are the Lord's."),
        DailyVerse(reference: "Romans 15:4", text: "For whatever was written in former days was written for our instruction, that through endurance and through the encouragement of the Scriptures we might have hope."),
        DailyVerse(reference: "1 Corinthians 1:9", text: "God is faithful, by whom you were called into the fellowship of his Son, Jesus Christ our Lord."),
        DailyVerse(reference: "1 Corinthians 2:9", text: "But, as it is written, What no eye has seen, nor ear heard, nor the heart of man imagined, what God has prepared for those who love him."),
        // Day 301-330
        DailyVerse(reference: "1 Corinthians 6:19-20", text: "Do you not know that your body is a temple of the Holy Spirit within you, whom you have from God? You are not your own, for you were bought with a price. So glorify God in your body."),
        DailyVerse(reference: "1 Corinthians 10:13", text: "No temptation has overtaken you that is not common to man. God is faithful, and he will not let you be tempted beyond your ability, but with the temptation he will also provide the way of escape."),
        DailyVerse(reference: "1 Corinthians 13:4-5", text: "Love is patient and kind; love does not envy or boast; it is not arrogant or rude. It does not insist on its own way; it is not irritable or resentful."),
        DailyVerse(reference: "1 Corinthians 13:7", text: "Love bears all things, believes all things, hopes all things, endures all things."),
        DailyVerse(reference: "1 Corinthians 13:13", text: "So now faith, hope, and love abide, these three; but the greatest of these is love."),
        DailyVerse(reference: "1 Corinthians 15:57-58", text: "But thanks be to God, who gives us the victory through our Lord Jesus Christ. Therefore, my beloved brothers, be steadfast, immovable, always abounding in the work of the Lord."),
        DailyVerse(reference: "2 Corinthians 1:3-4", text: "Blessed be the God and Father of our Lord Jesus Christ, the Father of mercies and God of all comfort, who comforts us in all our affliction, so that we may be able to comfort those who are in any affliction."),
        DailyVerse(reference: "2 Corinthians 3:17", text: "Now the Lord is the Spirit, and where the Spirit of the Lord is, there is freedom."),
        DailyVerse(reference: "2 Corinthians 4:16-17", text: "So we do not lose heart. Though our outer self is wasting away, our inner self is being renewed day by day. For this light momentary affliction is preparing for us an eternal weight of glory beyond all comparison."),
        DailyVerse(reference: "2 Corinthians 4:18", text: "As we look not to the things that are seen but to the things that are unseen. For the things that are seen are transient, but the things that are unseen are eternal."),
        DailyVerse(reference: "2 Corinthians 9:8", text: "And God is able to make all grace abound to you, so that having all sufficiency in all things at all times, you may abound in every good work."),
        DailyVerse(reference: "Galatians 2:20", text: "I have been crucified with Christ. It is no longer I who live, but Christ who lives in me. And the life I now live in the flesh I live by faith in the Son of God, who loved me and gave himself for me."),
        DailyVerse(reference: "Galatians 5:1", text: "For freedom Christ has set us free; stand firm therefore, and do not submit again to a yoke of slavery."),
        DailyVerse(reference: "Galatians 6:9", text: "And let us not grow weary of doing good, for in due season we will reap, if we do not give up."),
        DailyVerse(reference: "Ephesians 1:3", text: "Blessed be the God and Father of our Lord Jesus Christ, who has blessed us in Christ with every spiritual blessing in the heavenly places."),
        DailyVerse(reference: "Ephesians 2:10", text: "For we are his workmanship, created in Christ Jesus for good works, which God prepared beforehand, that we should walk in them."),
        DailyVerse(reference: "Ephesians 3:16-17", text: "That according to the riches of his glory he may grant you to be strengthened with power through his Spirit in your inner being, so that Christ may dwell in your hearts through faith."),
        DailyVerse(reference: "Ephesians 4:2-3", text: "With all humility and gentleness, with patience, bearing with one another in love, eager to maintain the unity of the Spirit in the bond of peace."),
        DailyVerse(reference: "Ephesians 4:32", text: "Be kind to one another, tenderhearted, forgiving one another, as God in Christ forgave you."),
        DailyVerse(reference: "Ephesians 5:1-2", text: "Therefore be imitators of God, as beloved children. And walk in love, as Christ loved us and gave himself up for us, a fragrant offering and sacrifice to God."),
        DailyVerse(reference: "Ephesians 6:11", text: "Put on the whole armor of God, that you may be able to stand against the schemes of the devil."),
        DailyVerse(reference: "Philippians 2:3-4", text: "Do nothing from selfish ambition or conceit, but in humility count others more significant than yourselves. Let each of you look not only to his own interests, but also to the interests of others."),
        DailyVerse(reference: "Philippians 2:13", text: "For it is God who works in you, both to will and to work for his good pleasure."),
        DailyVerse(reference: "Philippians 3:13-14", text: "Brothers, I do not consider that I have made it my own. But one thing I do: forgetting what lies behind and straining forward to what lies ahead, I press on toward the goal for the prize of the upward call of God."),
        DailyVerse(reference: "Philippians 4:4-5", text: "Rejoice in the Lord always; again I will say, rejoice. Let your reasonableness be known to everyone. The Lord is at hand."),
        DailyVerse(reference: "Philippians 4:8", text: "Finally, brothers, whatever is true, whatever is honorable, whatever is just, whatever is pure, whatever is lovely, whatever is commendable, if there is any excellence, if there is anything worthy of praise, think about these things."),
        DailyVerse(reference: "Philippians 4:19", text: "And my God will supply every need of yours according to his riches in glory in Christ Jesus."),
        DailyVerse(reference: "Colossians 1:17", text: "And he is before all things, and in him all things hold together."),
        DailyVerse(reference: "Colossians 2:6-7", text: "Therefore, as you received Christ Jesus the Lord, so walk in him, rooted and built up in him and established in the faith, just as you were taught, abounding in thanksgiving."),
        DailyVerse(reference: "Colossians 3:2", text: "Set your minds on things that are above, not on things that are on earth."),
        // Day 331-366
        DailyVerse(reference: "Colossians 3:12", text: "Put on then, as God's chosen ones, holy and beloved, compassionate hearts, kindness, humility, meekness, and patience."),
        DailyVerse(reference: "Colossians 3:16-17", text: "Let the word of Christ dwell in you richly, teaching and admonishing one another in all wisdom, singing psalms and hymns and spiritual songs, with thankfulness in your hearts to God."),
        DailyVerse(reference: "1 Thessalonians 5:11", text: "Therefore encourage one another and build one another up, just as you are doing."),
        DailyVerse(reference: "2 Thessalonians 3:3", text: "But the Lord is faithful. He will establish you and guard you against the evil one."),
        DailyVerse(reference: "1 Timothy 4:12", text: "Let no one despise you for your youth, but set the believers an example in speech, in conduct, in love, in faith, in purity."),
        DailyVerse(reference: "1 Timothy 6:6", text: "But godliness with contentment is great gain."),
        DailyVerse(reference: "2 Timothy 2:15", text: "Do your best to present yourself to God as one approved, a worker who has no need to be ashamed, rightly handling the word of truth."),
        DailyVerse(reference: "2 Timothy 3:16-17", text: "All Scripture is breathed out by God and profitable for teaching, for reproof, for correction, and for training in righteousness, that the man of God may be complete, equipped for every good work."),
        DailyVerse(reference: "2 Timothy 4:7", text: "I have fought the good fight, I have finished the race, I have kept the faith."),
        DailyVerse(reference: "Titus 3:5", text: "He saved us, not because of works done by us in righteousness, but according to his own mercy, by the washing of regeneration and renewal of the Holy Spirit."),
        DailyVerse(reference: "Hebrews 4:12", text: "For the word of God is living and active, sharper than any two-edged sword, piercing to the division of soul and of spirit, of joints and of marrow, and discerning the thoughts and intentions of the heart."),
        DailyVerse(reference: "Hebrews 10:23", text: "Let us hold fast the confession of our hope without wavering, for he who promised is faithful."),
        DailyVerse(reference: "Hebrews 10:35-36", text: "Therefore do not throw away your confidence, which has a great reward. For you have need of endurance, so that when you have done the will of God you may receive what is promised."),
        DailyVerse(reference: "Hebrews 11:6", text: "And without faith it is impossible to please him, for whoever would draw near to God must believe that he exists and that he rewards those who seek him."),
        DailyVerse(reference: "Hebrews 13:5-6", text: "Keep your life free from love of money, and be content with what you have, for he has said, I will never leave you nor forsake you. So we can confidently say, The Lord is my helper; I will not fear."),
        DailyVerse(reference: "Hebrews 13:8", text: "Jesus Christ is the same yesterday and today and forever."),
        DailyVerse(reference: "James 1:2-3", text: "Count it all joy, my brothers, when you meet trials of various kinds, for you know that the testing of your faith produces steadfastness."),
        DailyVerse(reference: "James 1:17", text: "Every good gift and every perfect gift is from above, coming down from the Father of lights, with whom there is no variation or shadow due to change."),
        DailyVerse(reference: "James 1:19", text: "Know this, my beloved brothers: let every person be quick to hear, slow to speak, slow to anger."),
        DailyVerse(reference: "James 1:22", text: "But be doers of the word, and not hearers only, deceiving yourselves."),
        DailyVerse(reference: "James 3:17", text: "But the wisdom from above is first pure, then peaceable, gentle, open to reason, full of mercy and good fruits, impartial and sincere."),
        DailyVerse(reference: "James 5:16", text: "Therefore, confess your sins to one another and pray for one another, that you may be healed. The prayer of a righteous person has great power as it is working."),
        DailyVerse(reference: "1 Peter 1:3", text: "Blessed be the God and Father of our Lord Jesus Christ! According to his great mercy, he has caused us to be born again to a living hope through the resurrection of Jesus Christ from the dead."),
        DailyVerse(reference: "1 Peter 2:9", text: "But you are a chosen race, a royal priesthood, a holy nation, a people for his own possession, that you may proclaim the excellencies of him who called you out of darkness into his marvelous light."),
        DailyVerse(reference: "1 Peter 3:15", text: "But in your hearts honor Christ the Lord as holy, always being prepared to make a defense to anyone who asks you for a reason for the hope that is in you; yet do it with gentleness and respect."),
        DailyVerse(reference: "1 Peter 4:8", text: "Above all, keep loving one another earnestly, since love covers a multitude of sins."),
        DailyVerse(reference: "1 Peter 5:6", text: "Humble yourselves, therefore, under the mighty hand of God so that at the proper time he may exalt you."),
        DailyVerse(reference: "2 Peter 1:3", text: "His divine power has granted to us all things that pertain to life and godliness, through the knowledge of him who called us to his own glory and excellence."),
        DailyVerse(reference: "2 Peter 3:9", text: "The Lord is not slow to fulfill his promise as some count slowness, but is patient toward you, not wishing that any should perish, but that all should reach repentance."),
        DailyVerse(reference: "1 John 3:1", text: "See what kind of love the Father has given to us, that we should be called children of God; and so we are."),
        DailyVerse(reference: "1 John 4:4", text: "Little children, you are from God and have overcome them, for he who is in you is greater than he who is in the world."),
        DailyVerse(reference: "1 John 4:7-8", text: "Beloved, let us love one another, for love is from God, and whoever loves has been born of God and knows God. Anyone who does not love does not know God, because God is love."),
        DailyVerse(reference: "1 John 5:4", text: "For everyone who has been born of God overcomes the world. And this is the victory that has overcome the world — our faith."),
        DailyVerse(reference: "1 John 5:14", text: "And this is the confidence that we have toward him, that if we ask anything according to his will he hears us."),
        DailyVerse(reference: "Jude 1:24-25", text: "Now to him who is able to keep you from stumbling and to present you blameless before the presence of his glory with great joy, to the only God, our Savior, through Jesus Christ our Lord, be glory, majesty, dominion, and authority."),
        DailyVerse(reference: "Revelation 3:20", text: "Behold, I stand at the door and knock. If anyone hears my voice and opens the door, I will come in to him and eat with him, and he with me."),
    ]

    static func verseForToday() -> DailyVerse {
        let dayOfYear = Calendar.current.ordinality(of: .day, in: .year, for: .now) ?? 1
        let index = (dayOfYear - 1) % verses.count
        return verses[index]
    }
}
