// Config.swift - Auto-generated at build time
// Virtual read-only view of public environment variables available to Swift code

import Foundation

enum Config {
    static let EXPO_PUBLIC_ANTHROPIC_API_KEY = ""
    static let EXPO_PUBLIC_API_BIBLE_KEY = ""
    static let EXPO_PUBLIC_APPLE_APP_ID = ""
    static let EXPO_PUBLIC_APPSFLYER_DEV_KEY = ""
    static let EXPO_PUBLIC_BRANCH_KEY = ""
    static let EXPO_PUBLIC_BRANCH_LINK_DOMAIN = ""
    static let EXPO_PUBLIC_PROJECT_ID = ""
    static let EXPO_PUBLIC_REVENUECAT_IOS_API_KEY = ""
    static let EXPO_PUBLIC_REVENUECAT_TEST_API_KEY = ""
    static let EXPO_PUBLIC_RORK_API_BASE_URL = ""
    static let EXPO_PUBLIC_RORK_AUTH_URL = ""
    static let EXPO_PUBLIC_RORK_TOOLKIT_SECRET_KEY = ""
    static let EXPO_PUBLIC_TEAM_ID = ""
    static let EXPO_PUBLIC_TOOLKIT_URL = ""

    static let allValues: [String: String] = [
        "EXPO_PUBLIC_ANTHROPIC_API_KEY": EXPO_PUBLIC_ANTHROPIC_API_KEY,
        "EXPO_PUBLIC_API_BIBLE_KEY": EXPO_PUBLIC_API_BIBLE_KEY,
        "EXPO_PUBLIC_APPLE_APP_ID": EXPO_PUBLIC_APPLE_APP_ID,
        "EXPO_PUBLIC_APPSFLYER_DEV_KEY": EXPO_PUBLIC_APPSFLYER_DEV_KEY,
        "EXPO_PUBLIC_BRANCH_KEY": EXPO_PUBLIC_BRANCH_KEY,
        "EXPO_PUBLIC_BRANCH_LINK_DOMAIN": EXPO_PUBLIC_BRANCH_LINK_DOMAIN,
        "EXPO_PUBLIC_PROJECT_ID": EXPO_PUBLIC_PROJECT_ID,
        "EXPO_PUBLIC_REVENUECAT_IOS_API_KEY": EXPO_PUBLIC_REVENUECAT_IOS_API_KEY,
        "EXPO_PUBLIC_REVENUECAT_TEST_API_KEY": EXPO_PUBLIC_REVENUECAT_TEST_API_KEY,
        "EXPO_PUBLIC_RORK_API_BASE_URL": EXPO_PUBLIC_RORK_API_BASE_URL,
        "EXPO_PUBLIC_RORK_AUTH_URL": EXPO_PUBLIC_RORK_AUTH_URL,
        "EXPO_PUBLIC_RORK_TOOLKIT_SECRET_KEY": EXPO_PUBLIC_RORK_TOOLKIT_SECRET_KEY,
        "EXPO_PUBLIC_TEAM_ID": EXPO_PUBLIC_TEAM_ID,
        "EXPO_PUBLIC_TOOLKIT_URL": EXPO_PUBLIC_TOOLKIT_URL,
    ]
}
